[connections.mydb]
host = "localhost"
port = "3306"
database = "adventurework"
username = "root"
password = ""

#dialect = "mysql"
#driver = "pymysql"
#host = "kubela.id"
#port = "3306"
#database = "aw"
#username = "davis2024irwan"
#password = "wh451n9m@ch1n3"